src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnimalRepository::class)]
class Animal
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_latin = null;

    #[ORM\ManyToOne(inversedBy: 'animaux')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Especes $especes = null;

    #[ORM\ManyToMany(targetEntity: Continent::class, mappedBy: 'animaux')]
    private Collection $continents;

    #[ORM\OneToMany(mappedBy: 'animal', targetEntity: Possede::class)]
    private Collection $possedes;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $poids = null;

    public function __construct()
    {
        $this->continents = new ArrayCollection();
        $this->possedes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getNomLatin(): ?string
    {
        return $this->nom_latin;
    }

    public function setNomLatin(string $nom_latin): static
    {
        $this->nom_latin = $nom_latin;

        return $this;
    }

    public function getEspeces(): ?Especes
    {
        return $this->especes;
    }

    public function setEspeces(?Especes $especes): static
    {
        $this->especes = $especes;

        return $this;
    }

    /**
     * @return Collection<int, Continent>
     */
    public function getContinents(): Collection
    {
        return $this->continents;
    }

    public function addContinent(Continent $continent): static
    {
        if (!$this->continents->contains($continent)) {
            $this->continents->add($continent);
            $continent->addAnimaux($this);
        }

        return $this;
    }

    public function removeContinent(Continent $continent): static
    {
        if ($this->continents->removeElement($continent)) {
            $continent->removeAnimaux($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Possede>
     */
    public function getPossedes(): Collection
    {
        return $this->possedes;
    }

    public function addPossede(Possede $possede): static
    {
        if (!$this->possedes->contains($possede)) {
            $this->possedes->add($possede);
            $possede->setAnimal($this);
        }

        return $this;
    }

    public function removePossede(Possede $possede): static
    {
        if ($this->possedes->removeElement($possede)) {
            // set the owning side to null (unless already changed)
            if ($possede->getAnimal() === $this) {
                $possede->setAnimal(null);
            }
        }

        return $this;
    }

    public function getPoids(): ?string
    {
        return $this->poids;
    }

    public function setPoids(?string $poids): static
    {
        $this->poids = $poids;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Prenom = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): static
    {
        $this->Prenom = $Prenom;

        return $this;
    }
}

src/Form/AnimalType.php
<?php

namespace App\Form;

use App\Entity\Animal;
use App\Entity\Continent;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Especes;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class AnimalType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('description')
            ->add('image')
            ->add('nom_latin')
            ->add('especes', EntityType::class, 
                   array('class' => Especes::class,
                        'choice_label'=>'Libelle',
                        'label' => 'Choisir espèces',
                        'multiple' => false))
            ->add('continents', EntityType::class, 
                    array('class' => Continent::class,
                        'choice_label'=>'libelle',
                        'label' => 'Choisir le continent où vit l\'animal',
                        'multiple' => true,
                        'expanded'=>true,
                        'by_reference'=>false ))           
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Animal::class,
        ]);
    }
}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Entity\Continent;
use App\Entity\Personne;
use App\Entity\Possede;
use App\Form\AnimalType;
use App\Form\ContinentType;
use App\Form\PersonneType;
use App\Repository\AnimalRepository;
use App\Repository\ContinentRepository;
use App\Repository\PersonneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class AnimalController extends AbstractController
{
                                // Animaux

//http://localhost:8000/animaux
    #[Route('/animaux', name: 'app_animaux')]
    public function liste(AnimalRepository $ar): Response
    {
        return $this->render('animal/liste.html.twig', [
            'Animaux' => $ar->findAll()
        ]);
    }
//http://localhost:8000/animal/id
    #[Route('/animal/{id}', name: 'app_animal')]
    public function animal(AnimalRepository $ar,$id): Response
    {
        return $this->render('animal/animal.html.twig', [
            'animal' => $ar->find($id)
        ]);
    }
//http://localhost:8000/createAnimal/id
// On utilise la même fonction que modif, en ajoutant 
// possibilité d'avoir animal et id null ainsi que if (!$animal) { $animal = new Animal ;} pour 
// indiquer la création d'un nouvel animal
// On peut avoir plusieurs routes pour la même fonction
#[Route('/creaanimal', name: 'creaanimal')] 
//http://localhost:8000/modifAnimal/id
    #[Route('/modifanimal/{id}', name: 'modif_animal')]
    public function modifAnimal(Animal $animal=null, Request $req, EntityManagerInterface $emi, 
    $id=null): Response
    {
        if (!$animal) {
            $animal = new Animal() ;
        }
        $form = $this->createForm(AnimalType::class, $animal);
        $form -> handleRequest($req) ; //Recupere les données
        if ($form->isSubmitted()) {
            $emi->persist($animal) ;
            $emi->flush() ;
            $this->addFlash("success","Modification effectuée");
        return $this->redirectToRoute('app_animaux');
        }
    return $this->render('animal/formanimal.html.twig',
        ['animal'=> $animal,
         'monform' => $form->createView()]);  
    }
//Delete un animal
    #[Route('/suppranimal/{id}', name :'suppr_animal')]
    public function supprAnimal(Animal $animal, Request $req, 
    EntityManagerInterface $emi, $id): Response
    {
        $emi->remove($animal) ;
        $emi->flush() ;
        return $this->redirectToRoute('app_animaux') ;
    }

                                // Continents

//http://localhost:8000/continents
    #[Route('/continents', name: 'app_continents')]
    public function listeContinent(ContinentRepository $cr): Response
    { 
        return $this->render('animal/continents.html.twig', [
            'Continents' => $cr->findAll()
        ]);
    }
//http:localhost:8000/continent/id
    #[Route('/continent/{id}', name: 'app_continent')]
    public function continent(ContinentRepository $cr,$id): Response
    {
        return $this->render('animal/continent.html.twig', [
            'continent' => $cr->find($id)
        ]);
    }
//http:localhost:8000/createContinent/id 
//http://localhost:8000/modifContinent/id
    #[Route('/creacontinent', name: 'creacontinent')] 
    #[Route('/modifcontinent/{id}', name: 'modif_continent')]
    public function modifContinent(Continent $continent=null, 
    Request $req, EntityManagerInterface $emi, 
    $id=null): Response
    {
        if (!$continent) {
            $continent = new Continent() ;
        }
        $form = $this->createForm(ContinentType::class, $continent);
        $form -> handleRequest($req) ; 
        if ($form->isSubmitted()) {
            $emi->persist($continent) ;
            $emi->flush() ;
        return $this->redirectToRoute('app_continents');
        }
    return $this->render('animal/formcontinent.html.twig',
        ['continent'=> $continent,
         'formcont' => $form->createView()]);  
    }
//Delete un continent
    #[Route('/supprcontinent/{id}', name :'suppr_continent')]
    public function supprContinent(Continent $continent, Request $req, 
    EntityManagerInterface $emi, $id): Response
    {
        $emi->remove($continent) ;
        $emi->flush() ;
        return $this->redirectToRoute('app_continents') ;
    }

                            // Personnes        

//http://localhost:8000/personnes
#[Route('/personnes', name: 'app_personnes')]
public function listePersonne(PersonneRepository $pr): Response
{ 
    return $this->render('animal/personnes.html.twig', [
        'Personnes' => $pr->findAll()
    ]);
}
//http:localhost:8000/personne/id
#[Route('/personne/{id}', name: 'app_personne')]
public function personne(PersonneRepository $pr,$id): Response
{
    return $this->render('animal/personne.html.twig', [
        'personne' => $pr->find($id)
    ]);
}
//http:localhost:8000/createpersonne/id 
//http://localhost:8000/modifpersonne/id
#[Route('/creapersonne', name: 'creapersonne')] 
#[Route('/modifpersonne/{id}', name: 'modif_personne')]
public function modifPersonne(Personne $personne=null, 
Request $req, EntityManagerInterface $emi, 
$id=null): Response
{
    if (!$personne) {
        $personne = new Personne() ;
    }
    $form = $this->createForm(PersonneType::class, $personne);
    $form -> handleRequest($req) ; 
    if ($form->isSubmitted()) {
        $emi->persist($personne) ;
        $emi->flush() ;
    return $this->redirectToRoute('app_personnes');
    }
return $this->render('animal/formpersonne.html.twig',
    ['personne'=> $personne,
     'formpers' => $form->createView()]);  
}
//Delete une personne
#[Route('/supprpersonne/{id}', name :'suppr_personne')]
public function supprPersonne(Personne $personne, Request $req, 
EntityManagerInterface $emi, $id): Response
{
    $emi->remove($personne) ;
    $emi->flush() ;
    return $this->redirectToRoute('app_personnes') ;
}


}

templates/animal/animal.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal{% endblock %}

{% block body %}
<style> 
</style>
{# {{ dump(animal) }} #}
    <div class="p-3 mb-2 bg-danger-subtle text-emphasis-danger">

    <h1> {{ animal.nom }} <br> </h1>
    <h5> {{ animal.nomLatin }} </h5>

    {% for continent in animal.continents %}
     <a href="/continent/{{continent.id}}">{{ continent.libelle }}</a>
    {% endfor %}

    </div>
    
    <p> <img src = "{{asset('img/'~animal.image)}}"> {{ animal.description | nl2br}} </p>
    <p> Le {{ animal.nom }} pese en moyenne {{animal.poids}} et fait partit de 
    la famille des {{ animal.especes.libelle }} </p> 

</div>
{% endblock %}

templates/animal/continent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Continents{% endblock %}

{% block body %}
<style></style>

<div class="p-3 mb-2 bg-success-subtle text-emphasis-success">

    <h1>Les animaux qui vivent en {{ continent.libelle }} </h1>
    
</div>  
    
   

    {% for animal in continent.animaux %}
    <br>
    <a href="/animal/{{animal.id}}"> {{ animal.nom }} </a>
    <br>
    <img src = "{{asset('img/'~animal.image)}}">
    {% endfor %}

    

{% endblock %}

templates/animal/continents.html.twig
{% extends 'base.html.twig' %}

{% block title %}Continents{% endblock %}

{% block body %}
<style></style>

<div class="p-3 mb-2 bg-warning-subtle text-emphasis-warning">

    <h1>Voici les continents avec les animaux qui y vivent</h1>
    <h6><a href="/creacontinent"> Create </a></h6>

</div>  
 
    {% for continent in Continents  %}
    <h2> <a href="/continent/{{continent.id}}"> {{ continent.libelle }} </a></h2>
    <p><a href="/modifcontinent/{{continent.id}}"> Update</a>
       <a href="/supprcontinent/{{continent.id}}"> Delete </a>
    </p>
    {% endfor %}

{% endblock %}

templates/animal/formanimal.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crea et modif Animal{% endblock %}

{% block body %}
<style>
.uneclasse {
    color:red; 
}
</style>

<div class="p-3 mb-2 bg-success text-white"><h1> Création et modification des animaux </h1></div>



    {{ form_start(monform)}} 
    <br>
    {# Pour personnaliser les inputs : #}

    <i class="fa fa-paw">{{ form_row(monform.nom, {
        'attr': {'class':'uneclasse' },
        })
    }}</i>
    <br>
    {{ form_widget(monform) }} 
    <br>
    <input type = 'submit' value = 'Envoyer'> 
    <br>    
    {{ form_end(monform) }} 
   
</div>
{% endblock %}

templates/animal/formcontinent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crea et modif Continent{% endblock %}

{% block body %}
<style>
.uneclasse {
    color:red; 
}
</style>

<div class="p-3 mb-2 bg-success text-white">
<h1> Création et modification des continents </h1>
</div>
 
    {{ form_start(formcont)}} 
    <br>
    {{ form_widget(formcont) }} 
    <br>
    <input type = 'submit' value = 'Envoyer'> 
    <br>    
    {{ form_end(formcont) }} 
   
{% endblock %}

templates/animal/formpersonne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crea et modif Personne{% endblock %}

{% block body %}
<style></style>

<div class="p-3 mb-2 bg-success text-white">

<h1> Création et modification des personnes </h1>
</div>

    {{ form_start(formpers)}} 
    <br>
    {{ form_widget(formpers) }} 
    <br>
    <input type = 'submit' value = 'Envoyer'> 
    <br>    
    {{ app.user }}
    dump {{user}}
    {{ form_end(formpers) }} 
   
{% endblock %}

templates/animal/liste.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste{% endblock %}

{% block body %}
<style>
body {
    margin:30px;
    background-color: #F2EBDC ;
}
</style>

<div >
    <h1 class="text-center">Voici la liste des animaux</h1>
    <h5 class="text-end mr-50"><a href="/modifanimal"> Create </a></h5>
</div>
  
<div class="row row-cols-lg-4 align-items-center text-center">
    {% for animal in Animaux  %}
    <div class="col-auto">
     <h2><a href="/animal/{{animal.id}}"> {{ animal.nom }} </a></h2>
     <img src = "{{asset('img/'~animal.image)}}">
     <p><a href="/modifanimal/{{animal.id}}"> Update</a>
     <a href="/suppranimal/{{animal.id}}"> Delete </a></p>
     </div>
    {% endfor %}
</div>
    
</div>
{% endblock %}

templates/animal/personne.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personne{% endblock %}

{% block body %}
<style></style>

<div class="p-3 mb-2 bg-danger-subtle text-emphasis-danger">

    <h1> {{ personne.nom }} </h1>
    <h1> {{ personne.prenom }} </h1>

</div>

{% endblock %}

templates/animal/personnes.html.twig
{% extends 'base.html.twig' %}

{% block title %}Personnes{% endblock %}

{% block body %}
<style></style>

<div class="p-3 mb-2 bg-warning-subtle text-emphasis-warning">

    <h1>Voici la liste des personnes possédant des animaux</h1>

    <h6><a href="/creapersonne"> Create </a></h6>

</div>
    
    {% for personne in Personnes  %}

     <h2><a href="/personne/{{personne.id}}"> 
     {{ personne.prenom }} {{ personne.nom }} 
     </a></h2>

     <p><a href="/modifpersonne/{{personne.id}}"> Update</a>
     <a href="/supprpersonne/{{personne.id}}"> Delete </a></p>
    {% endfor %}

</div>
{% endblock %}

templates/animal/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Crea et modif Personne{% endblock %}

{% block body %}
<style></style>

<div class="p-3 mb-2 bg-success text-white">

<h1> Création et modification des personnes </h1>
</div>

    
    dump {{ app.user }}
    
   
{% endblock %}